version: '3.7'

services:
  application:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./src:/src
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
